#!/usr/bin/perl -w

$linecount = 0;
while (@ARGV) {
	@lines = <>;
	chop @lines;
	
	foreach $line (@lines) {
		print ++$linecount," $line\n";
	}
	
	shift(@ARGV);
	if (@ARGV) {
		print ++$linecount,"\n";
	}
}
